#ifndef TITLE_HPP
#define TITLE_HPP

enum class Title {
    PROJECT_MANAGER,
    PROJECT_ASSISTANT,
    STAFF_SALES,
    CYLINDER_ENGINEER,
    EXTERN_SALES,
    INFRASTRUCTURE_ENGINEER,
    IT_SUPPORT_ENGINEER,
};

#endif